### PR TITLE
requests: better default error

### LINKED ISSUE #182: Log cluster members when can't connect
When faced with the infamous "Tried to connect to each peer twice and failed" message, it is very difficult to diagnose what actually went wrong.

It would be very helpful if the driver logged the machines in the cluster (or included it in the error message)

### PR DESCRIPTION
**Pull request by yichengq**
Default error contains cluster info and the last error received now.

fixes #182 , #185 

/cc @justinsb @willejs @kelseyhightower @xiang90 @thockin

### CODE REVIEW

**Comment by willejs** [comment]
:+1:

File: etcd/requests.go [hunk 1]
```diff
@@ -303,8 +303,8 @@ func DefaultCheckRetry(cluster *Cluster, numReqs int, lastResp http.Response,
 	err error) error {
 
 	if numReqs > 2*len(cluster.Machines) {
-		return newError(ErrCodeEtcdNotReachable,
-			"Tried to connect to each peer twice and failed", 0)
+		errStr := fmt.Sprintf("Tried to connect to members %v twice and failed: %v", cluster.Machines, err)
```
Comment (thockin) [inline etcd/requests.go]: It's still weird that you would even try twice if the error is not a "try again" error or a connection failure.  That the string says "tried to connect ... and failed" implies that there is an error with the connection, but there isn't.  It's better than before, but only in the most minimal possible way.

Comment (yichengq) [inline etcd/requests.go]: @thockin The function is used to check whether retry is reasonable. It can be called in two cases: 

1. there is an connection error. When there is a connection error, it deserves to do requests on other etcd members and it may succeed.

2. it receives a http response with bad status, e.g., StausInternalServerError, which may indicate the cluster is under leader election and we should wait for a while before retry.

It is reasonable to retry in both cases.

the `connect to` word is inaccurate, I will improve it.

Comment (yichengq) [inline etcd/requests.go]: /cc @dchen1107 @ArtfulCoder

Comment (thockin) [inline etcd/requests.go]: The error that brought me to this bug was "413 too large", which does not warrant a retry, and which your client will now report in the error string but will otherwise totally obfuscate.  So my assessment is still "better but barely".  This is such an important client lib it should really handle errors better, and that's not a 1-liner to fix.

**Comment by yichengq** [comment]
@thockin I think your concerns are reasonable. i change it to retry only when it is a connection error or should-retry response. PTAL.

File: etcd/requests.go [hunk 2]
```diff
@@ -302,21 +303,45 @@ func (c *Client) SendRequest(rr *RawRequest) (*RawResponse, error) {
...
 
-	code := lastResp.StatusCode
-	if code == http.StatusInternalServerError {
-		time.Sleep(time.Millisecond * 200)
-
+	if numReqs > 2*len(cluster.Machines) {
+		errStr := fmt.Sprintf("failed to propose on members %v twice [last error: %v]", cluster.Machines, err)
+		return newError(ErrCodeEtcdNotReachable, errStr, 0)
 	}
+	time.Sleep(time.Millisecond * 200)
```
Comment (thockin) [inline etcd/requests.go]: why are you sleeping in a library?  That's scary - at least warrants a comment?

**Comment by thockin** [comment]
this looks much better overall, thanks

File: etcd/requests.go (hunk 2 above)
Comment (yichengq) [inline etcd/requests.go]: It gives the cluster some time to finish leader election. Comments added.

**Comment by dchen1107** [comment]
Thanks for the fix.
